# Generated by Django 2.2.16 on 2020-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Personaje', verbose_name='Imagen')),
                ('date_old', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('age', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79)], default=1, verbose_name='Edad')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Male', max_length=6, verbose_name='Sexo')),
                ('reward', models.DecimalField(blank=True, decimal_places=3, max_digits=3, verbose_name='Recompensa')),
                ('fruit_name', models.CharField(blank=True, max_length=30, verbose_name='Nombre de fruta')),
                ('fruit_type', models.CharField(blank=True, choices=[('Paramecia', 'Paramecia'), ('Zoan', 'Zoan'), ('Logia', 'Logia'), ('None', 'None'), ('Unknown', 'Unknown')], default='Paramecia', max_length=20, verbose_name='Tipo de fruta')),
                ('race', models.CharField(choices=[('Human', 'Human'), ('Reindeer', 'Reindeer'), ('Gyoji', 'Gyoji'), ('Giant', 'Giant'), ('Triton', 'Triton'), ('Mink', 'Mink'), ('Long arms', 'Long arms'), ('Long legs', 'Long legs'), ('Three eyes', 'Three eyes'), ('Dwarf', 'Dwarf'), ('King', 'King'), ('Hybrid', 'Hybrid'), ('Cyborg', 'Cyborg'), ('Newkama', 'Newkama'), ('Zombie', 'Zombie'), ('Unknown', 'Unknown')], default='Human', max_length=20, verbose_name='Raza')),
                ('rank', models.CharField(choices=[('Supernova', 'Supernova'), ('Shichibukai', 'Shichibukai'), ('Yonkou', 'Yonkou'), ('Rey de los piratas', 'Rey de los piratas'), ('Capitan', 'Capitan'), ('Teniente', 'Teniente'), ('Oficial', 'Oficial'), ('Pirata', 'Pirata'), ('Gensual', 'Gensual'), ('Almirante', 'Almirante'), ('Vicealmirante', 'Vicealmirante'), ('Comodoro', 'Comodoro'), ('Famous', 'Famous'), ('Legend', 'Legend'), ('Unknown', 'Unknown')], default='Supernova', max_length=30, verbose_name='Rango')),
                ('state', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Unknown', 'Unknown')], default='Alive', max_length=6, verbose_name='Estado')),
                ('origin', models.CharField(blank=True, max_length=30, verbose_name='Origen')),
                ('attack', models.CharField(blank=True, choices=[('Golpe Relampago', 'Golpe Relampago'), ('Chancletazo', 'Chancletazo'), ('None', 'None'), ('Unknown', 'Unknown')], default='Golpe Relampago', max_length=30, verbose_name='Ataques')),
                ('occupation', models.CharField(choices=[('Capitan', 'Capitan'), ('Medico', 'Medico'), ('Espadachin', 'Espadachin'), ('Navegante', 'Navegante'), ('Francotirador', 'Francotirador'), ('Cocinero', 'Cocinero'), ('Aqueólogo', 'Aqueólogo'), ('Carpintero', 'Carpintero'), ('Músico', 'Músico'), ('Timonel', 'Timonel'), ('Sirviente', 'Sirviente'), ('Cientifico', 'Cientifico'), ('Pirata', 'Pirata'), ('Gobernate', 'Gobernate'), ('Samurai', 'Samurai'), ('Alcade', 'Alcade'), ('Assassin', 'Assassin'), ('Ministro', 'Ministro'), ('Cazarrecompensa', 'Cazarrecompensa'), ('Revolutionary', 'Revolutionary'), ('King', 'King'), ('None', 'None'), ('Unknown', 'Unknown')], default='Capitan', max_length=20, verbose_name='Ocupasion')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descriccion')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date published')),
                ('update_on', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
    ]
