# Generated by Django 2.2.16 on 2020-11-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='Recompensa'),
        ),
    ]
