# Generated by Django 2.2.16 on 2020-11-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('url', models.URLField(unique=True, verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Api Url',
                'verbose_name_plural': 'Api Urls',
            },
        ),
    ]
