# Generated by Django 2.2.16 on 2020-11-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Human', 'Human'), ('Reindeer', 'Reindeer'), ('Animal', 'Animal'), ('Gyoji', 'Gyoji'), ('Giant', 'Giant'), ('Triton', 'Triton'), ('Mink', 'Mink'), ('Long arms', 'Long arms'), ('Long legs', 'Long legs'), ('Three eyes', 'Three eyes'), ('Dwarf', 'Dwarf'), ('King', 'King'), ('Hybrid', 'Hybrid'), ('Cyborg', 'Cyborg'), ('Newkama', 'Newkama'), ('Zombie', 'Zombie'), ('Unknown', 'Unknown')], default='Human', max_length=20, verbose_name='Raza'),
        ),
    ]
