# Generated by Django 2.2.16 on 2020-11-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apiurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiurl',
            old_name='url',
            new_name='character',
        ),
        migrations.RemoveField(
            model_name='apiurl',
            name='name',
        ),
    ]
