# Generated by Django 2.2.16 on 2020-11-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201105_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='date_old',
        ),
    ]
