# Generated by Django 2.2.16 on 2020-11-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201111_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='state',
            new_name='status',
        ),
    ]
