# Generated by Django 2.2.16 on 2020-11-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201117_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiUrl',
        ),
    ]
