# Generated by Django 2.2.16 on 2020-11-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_destined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destined',
        ),
    ]
