# Generated by Django 2.2.16 on 2020-11-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=50, verbose_name='Nombre de fruta')),
                ('fruit_type', models.CharField(choices=[(1, 'Normal'), (2, 'Rara')], max_length=1, verbose_name='Tipo de fruta')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='Personaje', verbose_name='Imagen')),
                ('date_old', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('ega', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49)], max_length=1, verbose_name='Edad')),
                ('sex', models.CharField(choices=[(1, 'Mujer'), (2, 'Hombre')], max_length=1, verbose_name='Sexo')),
                ('value', models.IntegerField(verbose_name='Recompensa')),
                ('race', models.CharField(choices=[(1, 'Humano'), (2, 'Elfo')], max_length=1, verbose_name='Raza')),
                ('rank', models.CharField(choices=[(1, 'Soldado'), (2, 'Mayor')], max_length=1, verbose_name='Rango')),
                ('state', models.CharField(choices=[(1, 'Vivo'), (2, 'Muerto')], max_length=1, verbose_name='Estado')),
                ('origin', models.CharField(max_length=12, verbose_name='Origen')),
                ('attack', models.TextField(verbose_name='Ataques')),
                ('occupation', models.CharField(choices=[(1, 'Programador'), (2, 'Test')], max_length=1, verbose_name='Ocupasion')),
                ('description', models.TextField(verbose_name='Descriccion')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fruit')),
            ],
        ),
    ]
