# Generated by Django 2.2.16 on 2020-11-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='attack',
            field=models.CharField(choices=[(1, 'Golpe Relampago'), (2, 'Chancletazo')], default=1, max_length=1, verbose_name='Ataques'),
        ),
        migrations.AlterField(
            model_name='character',
            name='ega',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49)], default=1, max_length=1, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='character',
            name='occupation',
            field=models.CharField(choices=[(1, 'Programador'), (2, 'Test')], default=1, max_length=1, verbose_name='Ocupasion'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[(1, 'Humano'), (2, 'Elfo')], default=1, max_length=1, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='character',
            name='rank',
            field=models.CharField(choices=[(1, 'Soldado'), (2, 'Mayor')], default=1, max_length=1, verbose_name='Rango'),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(choices=[(1, 'Mujer'), (2, 'Hombre')], default=1, max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='character',
            name='state',
            field=models.CharField(choices=[(1, 'Vivo'), (2, 'Muerto')], default=1, max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='fruit_type',
            field=models.CharField(choices=[(1, 'Normal'), (2, 'Rara')], default=1, max_length=1, verbose_name='Tipo de fruta'),
        ),
    ]
